// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTd6YmDWTsuTxNknJU6goMbXayl0cHveA',
    appId: '1:542452045334:web:dd011ed22f4f11200fc737',
    messagingSenderId: '542452045334',
    projectId: 'agri-ac8e8',
    authDomain: 'agri-ac8e8.firebaseapp.com',
    storageBucket: 'agri-ac8e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYVVd_UAA2JRm9rwurWmFhq8QD0yJw4HY',
    appId: '1:542452045334:android:a6d6f3f2c9a74bc50fc737',
    messagingSenderId: '542452045334',
    projectId: 'agri-ac8e8',
    storageBucket: 'agri-ac8e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkZ0F0Y34tYWpp7I2FT82ZPalg-umhqSQ',
    appId: '1:542452045334:ios:1bd60e23881c213a0fc737',
    messagingSenderId: '542452045334',
    projectId: 'agri-ac8e8',
    storageBucket: 'agri-ac8e8.appspot.com',
    iosBundleId: 'com.example.agri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkZ0F0Y34tYWpp7I2FT82ZPalg-umhqSQ',
    appId: '1:542452045334:ios:1bd60e23881c213a0fc737',
    messagingSenderId: '542452045334',
    projectId: 'agri-ac8e8',
    storageBucket: 'agri-ac8e8.appspot.com',
    iosBundleId: 'com.example.agri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTd6YmDWTsuTxNknJU6goMbXayl0cHveA',
    appId: '1:542452045334:web:020d083637f03cfd0fc737',
    messagingSenderId: '542452045334',
    projectId: 'agri-ac8e8',
    authDomain: 'agri-ac8e8.firebaseapp.com',
    storageBucket: 'agri-ac8e8.appspot.com',
  );
}
